aws-configuration:
    region: us-west-2
    tags:
        - kafka-prod-server: "true"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/owl/.ssh/id_rsa

ansible-host: kafka
ansible-inventory-filename: /home/owl/Desktop/finaltestKafka/kafka
ansible-kafka-var-filename: /home/owl/Desktop/finaltestKafka/brokers.yml

