aws-configuration:
    region: us-west-2
    tags:
         tags-client:
               - client-node: "true"
         tags-zookeeper:
               - zookeeper-prod-server: "true"
         tags-kafka:
               - kafka-prod-server: "true" 
        
         tags-kafkaCandidate:
             - kafka-candidate: "true"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/owl/.ssh/id_rsa
ansible-host-client: client
ansible-host-kafka: kafka
ansible-host-zookeeper: zookeeper
ansible-inventory-filename-client: /home/owl/git-kafka/production/ansible/playbooks/client
ansible-clientIp-var-filename: /home/owl/git-kafka/production/ansible/playbooks/clientip.yml
ansible-inventory-filename-kafka: /home/owl/git-kafka/production/ansible/playbooks/kafka
ansible-kafka-var-filename: /home/owl/git-kafka/production/ansible/playbooks/brokers.yml
ansible-inventory-filename-zookeeper: /home/owl/git-kafka/production/ansible/playbooks/zookeeper
ansible-zookeeper-var-filename: /home/owl/git-kafka/production/ansible/playbooks/zookeeper.yml
kafkaBrokerCount: 3

