aws-configuration:
    region: us-west-2
    tags:
        - client-node: "true"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/owl/.ssh/id_rsa

ansible-host: client
ansible-inventory-filename: /etc/ansible/kafkaPlay/client

