aws-configuration:
    region: us-west-2
    tags:
        - kafka-prod-server: "true"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /home/owl/.ssh/id_rsa

ansible-host: kafka
ansible-inventory-filename: /etc/ansible/kafkaPlay/kafka

