version: '3'
services:
  kafka:
    build: ./kafka
    ports:
        - "9092:9092"
    environment:
        - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
    depends_on:
        - zookeeper
  zookeeper:
      build: ./zookeeper
      ports:
          - "2181:2181"
